---
- name: Setting up backend
  hosts: gluster_servers
  gather_facts: false

  vars:
     # Firewall setup
     gluster_infra_fw_ports:
        - 2049/tcp
        - 54321/tcp
        - 5900/tcp
        - 5900-6923/tcp
        - 5666/tcp
        - 16514/tcp
     gluster_infra_fw_services:
        - glusterfs

     # Set a disk type, Options: JBOD, RAID6, RAID10
     gluster_infra_disktype: JBOD


     gluster_infra_lvm: {
      autoexpand_threshold: 70,
      autoexpand_percentage: 15,
     }
   
     # enable fstrim service so the TRIM command is executed once in a while to clean either ssd or thin/vdo volumes
     fstrim_service: {
       enabled: yes,
       schedule: {         
         hour: "{{ range(1, 4) | random() }}"
       }
      }

     # Variables for creating volume group
     gluster_infra_volume_groups:
       - { vgname: 'vg_sdb', pvname: '/dev/sdb' }

     # Create thinpools
     gluster_infra_thinpools:
       #- {vgname: 'vg_sdb', thinpoolname: 'vg_sdb_thinpool', thinpoolsize: '7G', poolmetadatasize: '2G'}
       - {vgname: 'vg_sdb', thinpoolname: 'foo_thinpool', thinpoolsize: '7G', poolmetadatasize: '1G' }

     # Create a thin volume
     gluster_infra_lv_logicalvols:
       #- { vgname: 'vg_sdb',  thinpool: 'vg_sdb_thinpool', lvname: 'vg_sdb_thinlv', lvsize: '9G' }
       - { vgname: 'vg_sdb', thinpool: 'foo_thinpool', lvname: 'vg_sdb_thinlv', lvsize: '8G' }

     # Mount the devices
     gluster_infra_mount_devices:
       - { path: '/mnt/brick1', vgname: 'vg_sdb', lvname: 'vg_sdb_thinlv' }

  roles:
     - gluster.infra
