---
- name: Create Gluster cluster
  hosts: gluster_servers
  gather_facts: false

  vars:
    # gluster volume
    gluster_cluster_hosts:
      - 10.0.0.4
      - 10.0.0.5
      - 10.0.0.6
    gluster_cluster_volume: homedirs
    gluster_cluster_transport: 'tcp'
    gluster_cluster_force: 'yes'
    gluster_cluster_bricks: '/mnt/brick1/'

    # variables to create specific type of the volume
    gluster_cluster_replica_count: 3
    gluster_cluster_arbiter_count: 1

    # variables to set specific volume options
    gluster_cluster_options: {'performance.cache-size':'256MB'}

  roles:
    - gluster.cluster
