---
- hosts: all
  gather_facts: yes
  tasks:
  - name: set /etc/hosts 
    copy:
      src: content/etc/hosts
      dest: /etc/hosts
      mode: u+rw,a+r
      
  - name: Create parition on devices other than /dev/sda
    parted:
      device: "/dev/{{ item }}"
      number: 1
      state: present
    loop: "{{ ansible_devices.keys() | difference(['sda']) }}"

  - name: Format devices with xfs
    filesystem:
      fstype: xfs
      dev: "/dev/{{ item }}1"
    loop: "{{ ansible_devices.keys() | difference(['sda']) }}"

  - name: Mount devices under /data#
    mount:
      path: "/data-{{ item }}"
      src: "/dev/{{ item }}1"
      state: mounted
      fstype: xfs
    loop: "{{ ansible_devices.keys() | difference(['sda']) }}"

  - name: configure gluster repo
    yum_repository:
      name: "{{ glusterfs_package_full }}"
      description: Gluser HTTPS repo
      baseurl: "{{ glusterfs_repo_baseurl }}"
      enabled: yes
      gpgcheck: no

  - name: install epel-release
    yum:
      name: epel-release
      state: installed

  - name: Disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no

  - name: SELinux to permissive
    selinux:
      policy: targeted
      state: permissive

  - name: install "{{ glusterfs_package_full }}" 
    yum:
      name: "{{ glusterfs_package_name }}"
      state: installed

  - name: Enable "{{ glusterfs_package_name }}"
    systemd:
      name: glusterd
      state: started
      enabled: yes

  - name: Probing servers
    shell: gluster peer probe {{ item }}
    loop: "{{ groups[ group_names[0] ] }}"
